### ISSUE TITLE
It has no effect on some devices

### ISSUE THREAD

**Issue by beetxm** [keijiro/StableFluids#1]
Hello,
It is awesome!
But I got these errors on some devices that do not support Computer Shader, is there a solution?

RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
Graphics.CopyTexture source render texture could not be created.

**Comment by keijiro** [comment]
First of all, that error message doesn't mean a lack of computer shader support.

> RenderTexture.Create failed: format unsupported for random writes - RG16 SFloat (46).
> Graphics.CopyTexture source render texture could not be created.

It seems that your device doesn't support the RG16 texture format. You have to use another format instead.

---

Unfortunately, there is no instant solution to make StableFluids support compute-less devices. Although it's technically possible to implement the shader as a fragment shader, you have to rewrite lots of things (so it's not an instant solution).

**Comment by beetxm** [comment]
Thank you for your reply.
