### ISSUE TITLE
Transparent Texture

### ISSUE THREAD

**Issue by piankl** [keijiro/StableFluids#10]
Hi, thanks for this awesome shader.
Unfortunately, when I assign a transparent texture2d to _initial, it renders the background white.
How do I get it to render on an image with a transparent background instead?
thanks in advance.

**Comment by keijiro** [comment]
You should modify Fluid.shader as transparent.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further technical issue.
