### ISSUE TITLE
Dosen't support URP

### ISSUE THREAD

**Issue by mertcftci** [keijiro/StableFluids#14]
When I convert project to URP, screen goes black. Is there a working version compatible with URP?

**Comment by keijiro** [comment]
The shader itself is compatible with URP, but `Fuild.cs` doesn't support URP. Specifically saying, `OnRenderImage` is not supported by URP.

https://github.com/keijiro/StableFluids/blob/master/Assets/Fluid.cs#L219

> Is there a working version compatible with URP?

No.
