### ISSUE TITLE
I'm pretty new to unity and coding in general, I'm trying to get this to open in unity and it keeps saying "Package [Stable Fluids] Not found

### ISSUE THREAD

**Issue by FutTheWuk** [keijiro/StableFluids#16]
I'm not sure what I'm doing wrong. I opened the .json file with the package manager. Perhaps the files is too out of date, or perhaps (more likely) I'm misssing something.

**Comment by keijiro** [comment]
Honestly, I'm not sure what you're trying to do. This project doesn't contain any package. You should open the local copy of this project as a Unity project. Package Manager is not relevant.

**Comment by keijiro** [comment]
I close this issue now. Please reopen it for further problems.
