### ISSUE TITLE
Implementation without render texture

### ISSUE THREAD

**Issue by oct-test** [keijiro/StableFluids#2]
Hi,

I wanted to use your shaders to get the color mixing effect.[Link](https://www.youtube.com/watch?v=11UFYyv8hjs&feature=youtu.be&t=316).

I wanted to apply the color mixing effect only on the top face of the liquid (as shown in the ref video) and not on a full-screen image (like your tutorial).

What changes I have to make to get the desired effects? I would appreciate any suggestions and thoughts on this topic. Thank you.

**Comment by keijiro** [comment]
>  not on a full-screen image (like your tutorial).

I have never made any tutorial about this repository. I think you're looking at a wrong place. I'd recommend contacting a right person who created that "tutorial".

**Comment by devanshp915** [comment]
@oct-test wondering how you achieved that effect in the link, can you please share? :)
