### ISSUE TITLE
Making modifications at tapped position

### ISSUE THREAD

**Issue by oct-test** [keijiro/StableFluids#3]
Hello again,

I wanted to have texture deformation at the tapped position. For that, I am setting the "ForceOrigin" property of the compute shader using "**RaycastHit.textureCoord**" but the modification is not happening at the tapped location.

Any thoughts on how can I convert tapped position to a position that can be accepted by the compute shader? Thank you.

**Comment by keijiro** [comment]
First of all, I'd recommend checking if RaycastHit.textureCoord returns correct positions using Debug.Log or the script debugger.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by oct-test** [comment]
Hello,

The "RaycastHit.textureCoord" returns (0,0) for bottom left corner and (1,1) for top right corner as shown in the screenshot. However, when I set the "ForceOrigin" to (0,0), the deformation happens at the middle of the image.

**Comment by keijiro** [comment]
> Do I need to write some conversion logic to make it work?

maybe yes

**Comment by oct-test** [comment]
Thank you for your reply. The compute shader expects coordinates in which system?

**Comment by keijiro** [comment]
maybe (-1,-1) - (1, 1) ? sorry i can't remember it.
