### ISSUE TITLE
Performance optimisation

### ISSUE THREAD

**Issue by oct-test** [keijiro/StableFluids#4]
Hello again,

The plugin runs smoothly on iPhone 6s and above devices. However, the plugin lags a lot on iPad Air (1st generation). That iPad is quite old and I understand the hardware limitation of that iPad.

If I have to improve the performance of the plugin, are there any direct parameters that improve performance at cost of low-resolution output? Are there any passes in shader/script that can be removed without affecting the output majorly?

I would appericate any suggestions and thoughts on this topic. Thank you.

**Comment by keijiro** [comment]
> are there any direct parameters that improve performance at cost of low-resolution output?

Decrease the resolution.

https://github.com/keijiro/StableFluids/blob/master/Assets/Fluid.cs#L12

> Are there any passes in shader/script that can be removed without affecting the output majorly?

No.
