### ISSUE TITLE
Different behaviour on different iPhones

### ISSUE THREAD

**Issue by oct-test** [keijiro/StableFluids#5]
I am getting different behavior on different iPhones. On a few devices such as iPhone 6s and 7 Plus, for a small swipe on the surface, the liquid is displayed by a small amount. However, on iPhone X the liquid surface keeps moving even after I have stopped dragging a finger.

What could be the possible reason for such strange behavior?

**Comment by keijiro** [comment]
Maybe framerate affects it? I can't remember the details (I haven't touched this project for +2 years), but I'm pretty sure that the simulation is framerate-dependent. Lower framerate = Lower precision.

**Comment by oct-test** [comment]
Thank you for your reply. I will look into the code again and see if I could make the code framerate independent.

**Comment by oct-test** [comment]
Hello again. Here I have attached a video of the problem happening on the iPhone X. In this video, small drag action is performed and the liquid surface keeps on moving.

Link: https://drive.google.com/file/d/1_9nvYz81H-CUBJEPE3g1Ib21_Yzn-N-v/view?usp=sharing
