### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by FPGL-Aliumbasir** [keijiro/StableFluids#6]
Hello, this is a great shader.loving it in my personal experiments. But issue is with android build. When built the textures doesnt show up in phone. Any solutions?

**Comment by keijiro** [comment]
It requires Vulkan support.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

(If it reproduces even when you enable Vulkan on the device, please reopen it.)

**Comment by FPGL-Aliumbasir** [comment]
Thanks ,

Will try it.
