### ISSUE TITLE
Black screen on Android

### ISSUE THREAD

**Issue by moaazafzal** [keijiro/StableFluids#8]
Not working on android
even disable auto graphics API and add Vulkan
<img width="1440" alt="Screenshot 2021-05-15 at 6 32 54 PM" src="https://user-images.githubusercontent.com/45381597/118363053-ffc3f700-b5ab-11eb-8dcb-9778cddfdd25.png">

**Comment by keijiro** [comment]
I'm closing this issue now as duplication #7
