### ISSUE TITLE
Changing color & controlling spread

### ISSUE THREAD

**Issue by devanshp915** [keijiro/StableFluids#9]
Hey, would be great if anyone could help in figuring out how to make the player select what color he wants to apply. Also, wanted to know if there's a method to pause the spreading of color after a certain time? Unable to do this through viscosity/force, etc variables present there.

Thanks in advance!

**Comment by keijiro** [comment]
> how to make the player select what color he wants to apply. 

Draw anything into `_colorRT1`.

> here's a method to pause the spreading of color after a certain time

Modify the velocity field `VFB.V1` to freeze fluids.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
